function [M,R] = get_M_R(k,nMax,Lam,LamT,H,U0,N,f,nu,w0k)

% vector of m_n
m_ = (1:nMax)'*pi/H;

[A0,A1s,A2s,A3s,~] = get_AMatrices(nMax);
[Bsc,~] = get_BMatrices(nMax);
[s0,s1,s2,s3,s4,~,~] = get_sVectors(nMax);

kdim3 = reshape(k,[1,1,length(k)]);
w0kdim3 = reshape(w0k,[1,1,length(k)]);

if nu
    M = pagemtimes(1i*kdim3.^3 .* (U0^3*A0 + 3*U0^2*LamT*A1s + 3*U0*LamT^2*A2s + LamT^3*A3s) ...
                    + 3*nu*kdim3.^2 .* ((U0^2*A0 + 2*U0*LamT*A1s + LamT^2*A2s)*diag(m_.^2)) ...
                    - 3*nu^2*1i*kdim3 .* ((U0*A0 + LamT*A1s)*diag(m_.^4)) ...
                    - nu^3*diag(m_.^6) ...
                    - 2*nu*Lam^2*kdim3.^2 .* eye(nMax), ...
                                    kdim3.^2 .* eye(nMax) + diag(m_.^2)) ...
        ...
      - pagemtimes(1i*kdim3 .* (U0*A0 + LamT*A1s) + nu*diag(m_.^2), ...
                                    N^2*kdim3.^2 .* eye(nMax) + f^2*diag(m_.^2) ) ...
        ...
      - 2*f^2*Lam*1i*kdim3 .* (Bsc*diag(m_));
    
    R = w0kdim3 .* (1i*kdim3.^5 .* (U0^3*(s1 - s0) + 3*U0^2*LamT*(s2 - s1) ...
                    + 3*U0*LamT^2*(s3 - s2) + LamT^3*(s4 - s3)) ...
                  - 2*nu*Lam^2*kdim3.^4 .* (s1 - s0) ...
                  ...
                  - 1i*N^2*kdim3.^3 .* (U0*(s1 - s0) + LamT*(s2 - s1)) ...
                    ...
                  - 2*f^2*Lam*1i/H*kdim3 .* s0);
else
    M = pagemtimes(kdim3.^2 .* (U0^3*A0 + 3*U0^2*LamT*A1s + 3*U0*LamT^2*A2s + LamT^3*A3s), ...
                                    kdim3.^2 .* eye(nMax) + diag(m_.^2)) ...
        ...
      - pagemtimes(U0*A0 + LamT*A1s, ...
                                    N^2*kdim3.^2 .* eye(nMax) + f^2*diag(m_.^2) ) ...
        ...
      - 2*f^2*Lam .* (Bsc*diag(m_));

    R = w0kdim3 .* (kdim3.^4 .* (U0^3*(s1 - s0) + 3*U0^2*LamT*(s2 - s1) ...
                    + 3*U0*LamT^2*(s3 - s2) + LamT^3*(s4 - s3)) ...
                    ...
                  - N^2*kdim3.^2 .* (U0*(s1 - s0) + LamT*(s2 - s1)) ...
                    ...
                  - 2*f^2*Lam/H .* s0);
end